### ISSUE TITLE
Allspark is already taken

### ISSUE THREAD

**Issue by Thrashattack** [filipewvandrade/allspark#3]
We already have a project called `allspark` and `all-spark` in npm packages. 

I suggest `allspark-cli`

**Comment by andradefil** [comment]
What you think about `allspark-project`? 
I would like to add some AI in the future to help to estimate the cost in hours more automatically and the project probably will bebe growth, I think that maybe the `cli` will be just a type of client.

**Comment by Thrashattack** [comment]
Good suggest. Lets use that
